from __future__ import annotations

from collections import Counter
import json
import os
import re
import statistics


# --- Signal 1: Groq LLM attribution judgment ---------------------------------

GROQ_MODEL = "llama-3.3-70b-versatile"
_groq_client = None

LLM_SYSTEM_PROMPT = (
    "You are an AI-text attribution detector. Given a piece of text, estimate the "
    "probability that it was generated by an AI language model rather than written by "
    "a human. Respond with ONLY a JSON object of the exact form "
    '{"ai_probability": <number between 0 and 1>, "reason": "<one short sentence>"}. '
    "Higher means more likely AI-generated. Do not include any other text."
)


def _get_groq_client():
    """Lazily build a Groq client so import never fails when the key is absent."""
    global _groq_client
    if _groq_client is None:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set")
        from groq import Groq  # imported lazily so the module loads without the dep

        _groq_client = Groq(api_key=api_key)
    return _groq_client


def llm_ai_score(text: str) -> dict:
    """
    Signal 1: Groq LLM attribution judgment.

    Sends the text to a Groq-hosted LLM and asks for the probability that it was
    AI-generated. Returns a structured assessment:

        {"score": float | None, "reason": str, "available": bool}

    score is in [0.0, 1.0] (1.0 = strongly AI-like). On any failure (no key,
    network error, malformed response) returns available=False with a reason so
    the pipeline can fall back to the lexical heuristic and flag low reliability.
    """
    if not text or not text.strip():
        return {"score": None, "reason": "empty text", "available": False}

    try:
        client = _get_groq_client()
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": LLM_SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        data = json.loads(resp.choices[0].message.content)
        score = clamp(float(data["ai_probability"]))
        reason = str(data.get("reason", "")).strip()
        return {"score": round(score, 4), "reason": reason, "available": True}
    except Exception as e:  # noqa: BLE001 — degrade gracefully on any failure
        return {"score": None, "reason": f"llm error: {e}", "available": False}


# --- Fallback heuristic -------------------------------------------------------


def clamp(value: float, lower: float = 0.0, upper: float = 1.0) -> float:
    """Keep a score inside the 0.0 to 1.0 range."""
    return max(lower, min(upper, value))


def tokenize_words(text: str) -> list[str]:
    """Tokenize words in a simple, dependency-free way."""
    return re.findall(r"\b[a-zA-Z']+\b", text.lower())


def lexical_repetition_score(text: str) -> float:
    """
    Fallback heuristic: Lexical Diversity and Repetition Score.

    Used as the Signal-1 value only when the Groq LLM is unavailable
    (see ``llm_ai_score``), so the pipeline degrades gracefully instead of
    failing when the API/key is missing.

    Returns:
        float: A score from 0.0 to 1.0.
        - 0.0 means strongly human-like according to this signal.
        - 0.5 means neutral or not enough evidence.
        - 1.0 means strongly AI-like according to this signal.

    What it measures:
        - vocabulary diversity
        - repeated words
        - repeated two-word phrases

    Why short text returns neutral:
        With very short text, there is not enough evidence to measure repetition
        or lexical diversity fairly. The safest M3 behavior is a neutral score.
    """
    words = tokenize_words(text)

    if len(words) < 8:
        return 0.50

    total_words = len(words)
    word_counts = Counter(words)
    unique_words = len(word_counts)

    unique_word_ratio = unique_words / total_words
    diversity_ai_score = 1 - unique_word_ratio

    repeated_word_count = sum(1 for count in word_counts.values() if count > 1)
    repeated_word_ratio = repeated_word_count / unique_words if unique_words else 0.0

    bigrams = list(zip(words, words[1:]))
    if bigrams:
        bigram_counts = Counter(bigrams)
        repeated_bigram_instances = sum(count - 1 for count in bigram_counts.values() if count > 1)
        repeated_bigram_ratio = repeated_bigram_instances / len(bigrams)
    else:
        repeated_bigram_ratio = 0.0

    score = (
        diversity_ai_score
        + repeated_word_ratio
        + repeated_bigram_ratio
    ) / 3

    return round(clamp(score), 2)


# --- Signal 2: Sentence rhythm and structure variation -----------------------

_SENTENCE_SPLIT_RE = re.compile(r"[.!?]+")

# Mean-sentence-length normalization band (words). Averages at or below LOW read as
# choppy/casual (human-like); at or above HIGH read as long/dense (AI-like). Chosen
# so casual prose (~11 wpm) lands low and formal/AI prose (~20+ wpm) lands high.
_MEAN_LEN_LOW = 8.0
_MEAN_LEN_HIGH = 24.0


def split_sentences(text: str) -> list[str]:
    """Split text into non-empty, stripped sentences on . ! ? terminators."""
    return [p.strip() for p in _SENTENCE_SPLIT_RE.split(text) if p.strip()]


def sentence_rhythm_score(text: str) -> float:
    """
    Signal 2: Sentence rhythm and structure variation (stylometric heuristic).

    Returns a score from 0.0 to 1.0.
    - 0.0 means strongly human-like (varied/choppy rhythm) according to this signal.
    - 0.5 means neutral or not enough evidence.
    - 1.0 means strongly AI-like (uniform/dense rhythm) according to this signal.

    Combines TWO sentence-length statistics (both AI-like when high):
        1. length_uniformity  = 1 - normalized(std/avg)   -> low length variation
        2. mean_length_score  = normalized(avg sentence length) -> long, dense sentences
        sentence_rhythm_score = average(length_uniformity, mean_length_score)

    Calibration note (see planning.md "Signal 2 calibration"):
        The original spec's second metric, punctuation_variety (distinct marks / 6),
        was measured to be a biased non-discriminator: real prose uses only 1-2 of
        the six mark types, so it was a near-constant AI-ward push regardless of
        author. It was replaced with mean sentence length, which — like length
        variation — genuinely separates casual human writing from dense AI/formal
        prose.

    Insufficient-evidence guard:
        With fewer than two sentences there is no rhythm to measure, so the safest
        behavior is a neutral 0.50 (mirrors ``lexical_repetition_score``). This
        prevents a single short human sentence (variation 0 -> uniformity 1) from
        being flagged AI-like.
    """
    lengths = [len(tokenize_words(s)) for s in split_sentences(text)]
    lengths = [n for n in lengths if n > 0]

    if len(lengths) < 2:
        return 0.50

    avg_len = sum(lengths) / len(lengths)
    if avg_len == 0:
        return 0.50

    # Metric 1: sentence-length uniformity. The coefficient of variation is
    # unbounded, so clamp it before inverting (spec: normalized variation).
    cv = statistics.pstdev(lengths) / avg_len
    length_uniformity = 1 - clamp(cv)

    # Metric 2: mean sentence length, normalized to [0, 1] over the length band.
    mean_length_score = clamp((avg_len - _MEAN_LEN_LOW) / (_MEAN_LEN_HIGH - _MEAN_LEN_LOW))

    score = (length_uniformity + mean_length_score) / 2
    return round(clamp(score), 2)


# --- Combined confidence scoring (Confidence Scorer + Classification Mapper) --


def combine_signals(llm_ai_value: float, sentence_rhythm_value: float) -> float:
    """
    Combine both signals into a single ai_likelihood_score in [0.0, 1.0].

    Equal weights (0.50 / 0.50): the signals are complementary but each is
    incomplete, so neither should dominate. Rounded to 2 decimals per planning.md.
    """
    return round(0.50 * llm_ai_value + 0.50 * sentence_rhythm_value, 2)


def classify(ai_likelihood_score: float) -> str:
    """
    Map an ai_likelihood_score to a classification using planning.md's
    conservative thresholds:
    - >= 0.75: likely_ai
    - <= 0.25: likely_human
    - otherwise: uncertain
    """
    if ai_likelihood_score >= 0.75:
        return "likely_ai"
    if ai_likelihood_score <= 0.25:
        return "likely_human"
    return "uncertain"


def confidence_for(ai_likelihood_score: float) -> float:
    """
    Calibrated confidence for a given ai_likelihood_score (planning.md):
    - likely_ai (score >= 0.75):     confidence = score
    - likely_human (score <= 0.25):  confidence = 1 - score
    - uncertain:                     confidence = abs(score - 0.50) * 2

    In the uncertain band confidence measures distance from the 0.50 midpoint, so
    a score of exactly 0.50 yields 0.0 (maximally unsure), not 0.5.
    """
    if ai_likelihood_score >= 0.75:
        return round(ai_likelihood_score, 2)
    if ai_likelihood_score <= 0.25:
        return round(1 - ai_likelihood_score, 2)
    return round(abs(ai_likelihood_score - 0.50) * 2, 2)


# --- Transparency Label Generator --------------------------------------------

# Exact reader-facing label text per planning.md "Transparency Label Design".
# Keyed by the classification returned by ``classify``. The wording deliberately
# says "likely", never claims proven authorship, and invites appeal.
TRANSPARENCY_LABELS = {
    "likely_ai": (
        "This content was flagged as likely AI-generated based on multiple "
        "detection signals. This label is not a final judgment, and the creator "
        "may appeal the decision."
    ),
    "likely_human": (
        "This content was assessed as likely human-created based on multiple "
        "detection signals. No strong indicators of AI generation were found."
    ),
    "uncertain": (
        "This content could not be confidently classified as human-created or "
        "AI-generated. The result is uncertain, so readers should treat this "
        "label as contextual information rather than a final judgment."
    ),
}


def transparency_label(attribution: str) -> str:
    """
    Map a classification to its exact reader-facing transparency label.

    ``attribution`` is one of ``likely_ai`` / ``uncertain`` / ``likely_human``
    (the output of ``classify``). Falls back to the uncertain label for any
    unexpected value so the endpoint never returns an empty label.
    """
    return TRANSPARENCY_LABELS.get(attribution, TRANSPARENCY_LABELS["uncertain"])
